##
## Created by Charles MALHERBE and Arthur PERRET on 2022/11/22
##

SRC = ./src/*
OBJ = ./obj/*
INCLUDE = ./include/*

CC = gcc
CFLAGS = -Wall -g -I$(INCLUDE)

all: $(OBJ)
	$(CC) $(CFLAGS) main.c $(OBJ)

$(OBJ): $(SRC)
	$(CC) -c $(SRC) $(CFLAGS)
clean:
	rm -f $(OBJ) main

.PHONY: clean